name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    ## gradle build
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew bootJar


    ## 웹 이미지 빌드 및 도커허브에 push
    - name: web docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_REPO }}/ewm-eureka .
        docker push ${{ secrets.DOCKER_REPO }}/ewm-eureka
      
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          docker rmi taeyun1215/ewm-eureka
          docker pull ${{ secrets.DOCKER_REPO }}/ewm-eureka
        host: ${{ secrets.HOST }}
        user: ec2-user
        key: ${{ secrets.KEY}}
